### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by NeptuneDesign** [yeswecode/sail-bundle#10]
Hello,
Great idea for this package (I like laravel sail) ;)
However, when I type the command composer

```bash
composer require yeswecode/sail-bundle
```

This is displayed

```bash
 [InvalidArgumentException]
  Could not find a version of package yeswecode/sail-bundle matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

Thanks

**Comment by jakubtobiasz** [comment]
Hi!
Project is currently in the active development stage so it doesn't have a stable version yet. To try out the SailBundle you need to add
`"minimum-stability": "dev"`
in your composer.json file. I'll add this information in the README.md. 

ref: https://docs.yeswecode.pl/sailbundle/getting-started/installation (note is on the bottom of the page)

Hope this solve your issue and I can close the issue :).

**Comment by NeptuneDesign** [comment]
Thanks, it works for the moment, I'll test it ;)
If I have any problems I'll let you know.
Very good work.
Have a nice day.
